apiVersion: batch/v1
kind: Job
metadata:
  name: pi2
spec:
  #As Kubernetes Jobs are immutable and the template can't be changed once created
  #we can use ttlSecondsAfterFinished to clean them once execute so that our CD can redeploy/run them
  #again in case they are changed. This is a new feature in k8s 1.23.
  #If the value is 0 seconds the Job is inmmediatly deleted after execution.
  #If the field is unset the Job will behave as normal and won't be deleted automatically after execution.
  #ttlSecondsAfterFinished: 5
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: app-dogtest03test03
        image: k8s.gcr.io/busybox
        command: [ "sh", "-c"]
        args: ["while  true; do echo -en 'PI decimals: {{ .Values.piplaces }}.\n'; printenv MY_NODE_NAME MY_POD_NAME MY_POD_NAMESPACE; sleep 70;  break;       done; "]
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
  backoffLimit: 4
